version: '3.9'

services:
  reverse-proxy:
    container_name: reverse-proxy
    image: nginx:latest
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./localhost.crt:/etc/ssl/certs/localhost.crt
      - ./localhost.key:/etc/ssl/private/localhost.key
    depends_on:
      - client
    ports:
      - 443:443

  client:
    container_name: client
    image: client
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/node/
    volumes:
      - /home/node/node_modules
    